export const authCode = {
    FIELD_ALREADY_EXISTS: 'FIELD_ALREADY_EXISTS',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    UNAUTHORIZED: 'UNAUTHORIZED'
};
