export const authCode = {
    FIELD_REQUIRED: 'FIELD_REQUIRED',
    USERNAME_INVALID: 'USERNAME_INVALID',
    EMAIL_INVALID: 'EMAIL_INVALID',
    PASSWORD_WEAK: 'PASSWORD_WEAK',
    PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
    SERVER_ERROR: 'SERVER_ERROR',
    FIELD_ALREADY_EXISTS: 'FIELD_ALREADY_EXISTS',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    UNAUTHORIZED: 'UNAUTHORIZED'
};
