export const flowCode = {
    MISSING_FIELDS: 'MISSING_FIELDS',
    NAME_ALREADY_EXISTS: 'NAME_ALREADY_EXISTS',
    FLOW_NOT_FOUND: 'FLOW_NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    DUPLICATE_FAILED: 'DUPLICATE_FAILED',
    SERVER_ERROR: 'SERVER_ERROR'
};
