export const folderCode = {
    NAME_REQUIRED: 'NAME_REQUIRED',
    PLATFORM_REQUIRED: 'PLATFORM_REQUIRED',
    NAME_ALREADY_EXISTS: 'NAME_ALREADY_EXISTS',
    FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    DUPLICATE_FAILED: 'DUPLICATE_FAILED',
    DELETE_FAILED: 'DELETE_FAILED',
    FETCH_FAILED: 'FETCH_FAILED'
};
